export const TOURNAMENTS_PANEL = 'tournaments'
export const TOURNAMENT_PANEL = 'tournament'
export const GAME_PANEL = 'game'
export const TEAM_PANEL = 'team'
export const LEAGUE_PANEL = 'league'
export const ADD_WIDGET_PANEL = 'add_widget'